// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_GsK5VgknI2tn4ojGlCEW4-Xgb-DMJbQ',
    appId: '1:708057771404:web:174b25faa2d48867867aa9',
    messagingSenderId: '708057771404',
    projectId: 'paymentapp-a048c',
    authDomain: 'paymentapp-a048c.firebaseapp.com',
    storageBucket: 'paymentapp-a048c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKNCg6GfE7NtBzHYfgObsJQGRy-0QLxw0',
    appId: '1:708057771404:android:a0fdd289de37764e867aa9',
    messagingSenderId: '708057771404',
    projectId: 'paymentapp-a048c',
    storageBucket: 'paymentapp-a048c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiYfE2dNJT_zjzwfp6f_A0kFElWgA9KmE',
    appId: '1:708057771404:ios:aa5a2df305eb3eb7867aa9',
    messagingSenderId: '708057771404',
    projectId: 'paymentapp-a048c',
    storageBucket: 'paymentapp-a048c.firebasestorage.app',
    iosBundleId: 'com.example.stripeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiYfE2dNJT_zjzwfp6f_A0kFElWgA9KmE',
    appId: '1:708057771404:ios:aa5a2df305eb3eb7867aa9',
    messagingSenderId: '708057771404',
    projectId: 'paymentapp-a048c',
    storageBucket: 'paymentapp-a048c.firebasestorage.app',
    iosBundleId: 'com.example.stripeapp',
  );
}
